# Packages: base R, BiocManager installer. Input: project root from script path.
# Output: project-only R library, dependency inventory and installation log.
# Seed and dependency versions are defined in the study/environment files.
args <- commandArgs(trailingOnly=FALSE)
script <- sub("^--file=", "", args[grepl("^--file=", args)])
root <- normalizePath(file.path(dirname(script), ".."), winslash="/", mustWork=TRUE)
lib <- file.path(root,"environment","R-library")
dir.create(lib,recursive=TRUE,showWarnings=FALSE)
.libPaths(c(lib,.Library))
options(timeout=1800, repos=c(CRAN="https://cloud.r-project.org"), Ncpus=1)
set.seed(as.integer(Sys.getenv("STUDY_SEED")))
cran <- c("BiocManager","jsonlite","data.table","ggplot2","readxl","renv","sys")
local <- rownames(installed.packages(lib.loc=lib))
needed <- setdiff(cran,local)
if(length(needed)) install.packages(needed,lib=lib,type="binary")
bioc <- c("GenomeInfoDbData","limma","edgeR","AnnotationDbi","org.Hs.eg.db","org.Mm.eg.db","hugene10sttranscriptcluster.db","oligo","pd.hugene.1.0.st.v1")
local <- rownames(installed.packages(lib.loc=lib))
needed <- setdiff(bioc,local)
if("GenomeInfoDbData" %in% needed) BiocManager::install("GenomeInfoDbData",version="3.20",lib=lib,ask=FALSE,update=FALSE)
needed <- setdiff(needed,"GenomeInfoDbData")
if(length(needed)) BiocManager::install(needed,version="3.20",lib=lib,ask=FALSE,update=FALSE)
ok <- vapply(c(cran,bioc),requireNamespace,quietly=TRUE,FUN.VALUE=logical(1))
ip <- as.data.frame(installed.packages(lib.loc=lib),stringsAsFactors=FALSE)
write.csv(ip[,intersect(c("Package","Version","LibPath","Repository","Built"),names(ip))],file.path(root,"outputs","audit","r_packages.csv"),row.names=FALSE)
writeLines(capture.output(sessionInfo()),file.path(root,"outputs","audit","R_sessionInfo.txt"))
if(!all(ok)) stop(paste("Missing packages:",paste(names(ok)[!ok],collapse=", ")))
cat("R_CORE_PACKAGES_READY\n")
